package com.zhaofeng.deliverymanagement.entity;

public class DeliveryOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.delivery_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private Integer deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.order_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.delivery_id
     *
     * @return the value of delivery_order.delivery_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.delivery_id
     *
     * @param deliveryId the value for delivery_order.delivery_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.order_id
     *
     * @return the value of delivery_order.order_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.order_id
     *
     * @param orderId the value for delivery_order.order_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}