package com.zhaofeng.deliverymanagement.entity;

public class Truck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.lisence_plate
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private String lisencePlate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.id
     *
     * @return the value of truck.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.id
     *
     * @param id the value for truck.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.lisence_plate
     *
     * @return the value of truck.lisence_plate
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public String getLisencePlate() {
        return lisencePlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.lisence_plate
     *
     * @param lisencePlate the value for truck.lisence_plate
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setLisencePlate(String lisencePlate) {
        this.lisencePlate = lisencePlate;
    }
}