package com.zhaofeng.deliverymanagement.entity;

public class UserDeliveryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_delivery.user_id
     *
     * @mbg.generated Mon Jun 24 21:51:21 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_delivery.delivery_id
     *
     * @mbg.generated Mon Jun 24 21:51:21 CST 2019
     */
    private Integer deliveryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_delivery.user_id
     *
     * @return the value of user_delivery.user_id
     *
     * @mbg.generated Mon Jun 24 21:51:21 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_delivery.user_id
     *
     * @param userId the value for user_delivery.user_id
     *
     * @mbg.generated Mon Jun 24 21:51:21 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_delivery.delivery_id
     *
     * @return the value of user_delivery.delivery_id
     *
     * @mbg.generated Mon Jun 24 21:51:21 CST 2019
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_delivery.delivery_id
     *
     * @param deliveryId the value for user_delivery.delivery_id
     *
     * @mbg.generated Mon Jun 24 21:51:21 CST 2019
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }
}