package com.zhaofeng.deliverymanagement.entity;

public class UserOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.user_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.user_id
     *
     * @return the value of user_order.user_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.user_id
     *
     * @param userId the value for user_order.user_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_id
     *
     * @return the value of user_order.order_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_id
     *
     * @param orderId the value for user_order.order_id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}