package com.zhaofeng.deliverymanagement.model.entity;

public class Cement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cement.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cement.name
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cement.id
     *
     * @return the value of cement.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cement.id
     *
     * @param id the value for cement.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cement.name
     *
     * @return the value of cement.name
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cement.name
     *
     * @param name the value for cement.name
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}