package com.zhaofeng.deliverymanagement.model.entity;

import java.util.Date;

public class Delivery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.truck_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    private Integer truckId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.driver_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.delivery_time
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.user_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.id
     *
     * @return the value of delivery.id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.id
     *
     * @param id the value for delivery.id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.truck_id
     *
     * @return the value of delivery.truck_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public Integer getTruckId() {
        return truckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.truck_id
     *
     * @param truckId the value for delivery.truck_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public void setTruckId(Integer truckId) {
        this.truckId = truckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.driver_id
     *
     * @return the value of delivery.driver_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.driver_id
     *
     * @param driverId the value for delivery.driver_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.delivery_time
     *
     * @return the value of delivery.delivery_time
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.delivery_time
     *
     * @param deliveryTime the value for delivery.delivery_time
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.user_id
     *
     * @return the value of delivery.user_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.user_id
     *
     * @param userId the value for delivery.user_id
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}