package com.zhaofeng.deliverymanagement.model.entity;

public class DeliveryLoader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_loader.id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_loader.delivery_id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    private Integer deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_loader.loader_id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    private Integer loaderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_loader.id
     *
     * @return the value of delivery_loader.id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_loader.id
     *
     * @param id the value for delivery_loader.id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_loader.delivery_id
     *
     * @return the value of delivery_loader.delivery_id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_loader.delivery_id
     *
     * @param deliveryId the value for delivery_loader.delivery_id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_loader.loader_id
     *
     * @return the value of delivery_loader.loader_id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    public Integer getLoaderId() {
        return loaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_loader.loader_id
     *
     * @param loaderId the value for delivery_loader.loader_id
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    public void setLoaderId(Integer loaderId) {
        this.loaderId = loaderId;
    }
}