package com.zhaofeng.deliverymanagement.model.entity;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.name
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id
     *
     * @return the value of job.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id
     *
     * @param id the value for job.id
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.name
     *
     * @return the value of job.name
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.name
     *
     * @param name the value for job.name
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}