package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.Delivery;

public interface DeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Mon Jun 24 15:26:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Mon Jun 24 15:26:49 CST 2019
     */
    int insert(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Mon Jun 24 15:26:49 CST 2019
     */
    int insertSelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Mon Jun 24 15:26:49 CST 2019
     */
    Delivery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Mon Jun 24 15:26:49 CST 2019
     */
    int updateByPrimaryKeySelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Mon Jun 24 15:26:49 CST 2019
     */
    int updateByPrimaryKey(Delivery record);
}