package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.model.entity.DeliveryLoaderKey;

public interface DeliveryLoaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int deleteByPrimaryKey(DeliveryLoaderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insert(DeliveryLoaderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insertSelective(DeliveryLoaderKey record);
}