package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.model.entity.DeliveryLoader;

public interface DeliveryLoaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    int insert(DeliveryLoader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    int insertSelective(DeliveryLoader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    DeliveryLoader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    int updateByPrimaryKeySelective(DeliveryLoader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_loader
     *
     * @mbg.generated Wed Jun 26 20:53:03 CST 2019
     */
    int updateByPrimaryKey(DeliveryLoader record);
}