package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.DeliveryOrderKey;

public interface DeliveryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int deleteByPrimaryKey(DeliveryOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insert(DeliveryOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insertSelective(DeliveryOrderKey record);
}