package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.Delivery;
import com.zhaofeng.deliverymanagement.pojo.DeliveryPojo;

import java.util.List;

public interface DeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    int insert(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    int insertSelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    Delivery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    int updateByPrimaryKeySelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated Tue Jun 25 00:59:49 CST 2019
     */
    int updateByPrimaryKey(Delivery record);
    
    /**
     *
     * @param
     * @return 
     */
    List<DeliveryPojo> selectAllDeliveryDetailByUserId(Integer userId);
}