package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.Orders;
import com.zhaofeng.deliverymanagement.pojo.OrdersPojo;

import java.util.List;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:30:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:30:06 CST 2019
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:30:06 CST 2019
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:30:06 CST 2019
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:30:06 CST 2019
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:30:06 CST 2019
     */
    int updateByPrimaryKey(Orders record);


    /**
     * 根据用户id获取订单
     *
     * @param
     * @return 
     */
    List<OrdersPojo> selectAllOrdersByUserId(Integer userId);

    /**
     * 根据发货记录id查询订单
     *
     * @param
     * @return
     */
    List<OrdersPojo> selectAllOrdersByDeliveryId(Integer deliveryId);
}