package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.model.dto.TruckDTO;
import com.zhaofeng.deliverymanagement.model.entity.Truck;

import java.util.List;

public interface TruckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Tue Jun 25 20:44:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Tue Jun 25 20:44:02 CST 2019
     */
    int insert(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Tue Jun 25 20:44:02 CST 2019
     */
    int insertSelective(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Tue Jun 25 20:44:02 CST 2019
     */
    Truck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Tue Jun 25 20:44:02 CST 2019
     */
    int updateByPrimaryKeySelective(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Tue Jun 25 20:44:02 CST 2019
     */
    int updateByPrimaryKey(Truck record);

    /**
     * 根据用户id获取车辆
     *
     * @param
     * @return 
     */
    List<TruckDTO> selectByUserId(Integer userId);
    
    /**
     * 根据用户id获取指定车牌号的数量
     *
     * @param
     * @return 
     */
    Integer countByUserIdAnLicensePlate(Integer userId, String licensePlate);
}