package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.Truck;

public interface TruckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insert(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insertSelective(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    Truck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int updateByPrimaryKeySelective(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int updateByPrimaryKey(Truck record);
}