package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.UserOrderKey;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int deleteByPrimaryKey(UserOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insert(UserOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insertSelective(UserOrderKey record);
}