package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.UserAddressKey;

public interface UserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon Jun 24 20:13:04 CST 2019
     */
    int deleteByPrimaryKey(UserAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon Jun 24 20:13:04 CST 2019
     */
    int insert(UserAddressKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon Jun 24 20:13:04 CST 2019
     */
    int insertSelective(UserAddressKey record);
}