package com.zhaofeng.deliverymanagement.repository;

import com.zhaofeng.deliverymanagement.entity.UserRoleKey;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int deleteByPrimaryKey(UserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insert(UserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Mon Jun 24 14:36:42 CST 2019
     */
    int insertSelective(UserRoleKey record);
}